rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
install: 'bundle install -j 4'
script: 'bundle exec rake'
matrix:
  allow_failures:
    - rvm: jruby-19mode
