sudo: false
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
before_install:
  - gem update --system
  - gem install bundler
script: 'bundle exec rake'
